name: Generate Sitemap
on:
  push:
    branches:
      - main  # Or your main branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cicirello/generate-sitemap@main
        with:
          path-to-root: .  # Path to the root of your website (usually .)
          base-url-path: https://www.professional-websites-developer.co # Your GitHub Pages URL
          include-html: true  # Include HTML files (default is true)
          include-pdf: false  # Include PDF files (default is false)
          exclude-files: |  # Optional: Exclude specific files or paths
            - path/to/exclude/file.html
            - directory/to/exclude/*
